### ISSUE TITLE
Add ability to hide top circle

### ISSUE THREAD

**Issue by sgruby** [candostdagdeviren/CDAlertView#14] opened 2017-01-05 17:31 UTC
I'd like the ability to easily hide the top circle and just have a standard alert where I can control the font sizes.

**Comment by candostdagdeviren** [comment] 2017-01-09 07:51
This feature request already exists. I added a new explanation for the issue #6 

Duplicate of #6.

**Closed as completed** 2017-01-09 07:52 UTC
