### ISSUE TITLE
Message in alert is getting truncated

### ISSUE THREAD

**Issue by Kalikanth** [candostdagdeviren/CDAlertView#29] opened 2017-11-06 16:00 UTC
In my app presenting an alert but the message getting truncated to one line
```
let alert = CDAlertView(title: title, message: message, type: CDAlertViewType.error)
let okay = CDAlertViewAction(title: "OK", font: nil, textColor: nil, backgroundColor: nil) { (action) in
}
alert.add(action: okay)
alert.show()
```
![screen shot 2017-11-06 at 9 16 06 pm](https://user-images.githubusercontent.com/29298122/32450235-b774cd66-c339-11e7-842a-65748a834937.png)

**Comment by candostdagdeviren** [comment] 2017-11-06 16:28
Hello @Kalikanth, thanks for the issue! Which iOS and CDAlertView version do you use?

**Comment by Kalikanth** [comment] 2017-11-06 16:51
@candostdagdeviren  I'm using the latest version of CDAlertView (swift 4)and device is iPhone 6(11.0) xcode 9.1

**Comment by Kalikanth** [comment] 2017-11-07 05:43
What may be the issue. In other projects Default UIAlertController is working fine but after removing the CDAlertView. The UIAlertController also started truncating. How to overcome this please help this is very urgent.

**Comment by candostdagdeviren** [comment] 2017-11-07 06:02
![simulator screen shot - iphone 6 - 2017-11-07 at 07 01 03](https://user-images.githubusercontent.com/1971963/32479304-74c82030-c389-11e7-86cf-b7e60ee586e3.png)

I tried your code on iPhone 6, iOS 11.1 and it's working. Do you do extra customizations or something else that can override `UILabel`'s `numberOfLines` property?

**Comment by Kalikanth** [comment] 2017-11-07 06:29
i didn't do any customizations i'm not getting what's the problem what i obeserved is UILabels text is also getting truncated. How can set the this to default of UILabel

**Comment by candostdagdeviren** [comment] 2017-11-07 12:33
as you can see in here for message label: https://github.com/candostdagdeviren/CDAlertView/blob/master/CDAlertView/Classes/CDAlertView.swift#L578

and here for title label: https://github.com/candostdagdeviren/CDAlertView/blob/master/CDAlertView/Classes/CDAlertView.swift#L569

We set `numberOfLines` to 0. It shouldn't truncate. Do you have any extension of `UILabel` that can override this or something else which can cause this? Because I'm not able to reproduce the bug. Maybe you don't do any customizations for `CDAlertView` but you may customize `UILabel`'s properties or something else. This is the only thing that comes to my mind.

**Comment by Kalikanth** [comment] 2017-11-08 05:34
Yeah! I got the issue i was overriding the UILabel Property that is the reason for this strange behaviour. Thank you @candostdagdeviren

**Comment by candostdagdeviren** [comment] 2017-11-08 10:23
Good to see that you've solved! Closing the issue :)

**Closed as completed by candostdagdeviren** 2017-11-08 10:23 UTC
